CREATE DATABASE IF NOT EXISTS `quasar_tutorial` CHARACTER SET utf8 COLLATE utf8_general_ci;

USE quasar_tutorial;

CREATE TABLE  `users` (
`id` INT AUTO_INCREMENT PRIMARY KEY ,
`name` VARCHAR( 100 ) NOT NULL ,
`email` VARCHAR( 100 ) NOT NULL ,
`mobile` VARCHAR( 100 ) NOT NULL
) ENGINE = INNODB;